name: Update Data

on:
  workflow_dispatch:
  schedule:    
    - cron: "*/20 * * * *"
  
jobs:
  execute:
    runs-on: ubuntu-latest
    
    env:
      HOST: 'feedback.poeoverlay.com'
      BOARD: 'feedback'
      SOURCE: './data/posts.json'
      AVATAR_URL: 'https://cdn.discordapp.com/icons/678258268245852180/22a87b08892a574973f8c2b1d83bf85c.png'
      WEBHOOK: ${{ secrets.WEBHOOK }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          
      - run: yarn install
      - run: yarn run execute
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '- updated data'
