name: Update Data

on:
  workflow_dispatch:
  schedule:    
    - cron: "*/20 * * * *"
  
jobs:
  execute:
    runs-on: ubuntu-latest
    
    env:
      SUBDOMAIN: 'poe-overlay'
      BOARD: 'feedback'
      SOURCE: './data/posts.json'
      AVATAR_URL: 'https://cdn.discordapp.com/avatars/891586647014141995/37f44a33775cfb4f7b90aa36ef2b1964.png?size=256'
      WEBHOOK: ${{ secrets.WEBHOOK }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          
      - run: yarn install
      - run: yarn run execute
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '- updated data'
