name: Update Data

on:
  workflow_dispatch:
  
jobs:
  execute:
    runs-on: ubuntu-latest
    
    env:
      SUBDOMAIN: 'poe-overlay'
      SOURCE: './data/posts.json'
      WEBHOOK: ${{ secrets.WEBHOOK }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          
      - run: yarn install
      - run: yarn run execute
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '- updated data'
